import { Space_Mono } from "next/font/google";
import { Fraunces } from "next/font/google";
import "./globals.css";

const space = Space_Mono({ subsets: ["latin"], weight: ["700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={space.className}>
        {children}
      </body>
    </html>
  );
}
