import { Space_Mono, Fraunces } from "next/font/google";
import Nav from "./components/Navbar";
import LanguageSwitcher from "./components/LanguageSwitcher";
import Footer from "./components/Footer";
import "../globals.css";
import { dir } from 'i18next';
import { languages } from '../i18n/settings';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const space = Space_Mono({ subsets: ["latin"], weight: ["700"], display: "swap", });
export const fraunces = Fraunces({ subsets: ["latin"], weight: ["700"], display: "swap" });

export const metadata = {
  title: "Rina Reimer",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const lng = 'en';
  
  return (
    <html lang={lng} dir='ltr'>
      <body className= {`${space.className}`}>
        {/* <LanguageSwitcher lng={lng} /> */}
        <Nav lng={lng} /> 
        {children}
        {/* insert footer here */}
        {/* <Footer lng={lng} /> */}
      </body>
    </html>
  );
}
